name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
      branches: ["main"]
env:
  AWS_REGION: 

permissions:
  id-token: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 #v5.5.0
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install semgrep safety
    # ✔️ SECURITY ISSUE: Not running security tests
    - name: Run semgrep
      working-directory: ./app
      run: |
        semgrep ci --config auto --json --json-output=semgrep.json
    - name: Run safety
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2
      # ✔️ SECURITY ISSUE: Not pinning action version with SHA
    
    - name: Set up Python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e #v2
      # ✔️ SECURITY ISSUE: Not pinning action version with SHA
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
        pip install pytest
    
    - name: Run tests
      working-directory: ./app
      run: |
        pytest

    - name: Build Docker image
      working-directory: ./app
      run: |
        docker build -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} .

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        role-session-name: github-oidc
        aws-region: ${{ vars.AWS_REGION }}
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
    
    - name: Push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker tag  ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
        docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # SECURITY ISSUE: No environment-specific deployment
    # SECURITY ISSUE: No approval gate for production deployment
    
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name my-cluster --region ${{ vars.AWS_REGION }}
    
    - name: Deploy to Kubernetes
      run: |
        # SECURITY ISSUE: No validation of Kubernetes manifests
        kubectl apply -f infra/deployment.yaml
        # SECURITY ISSUE: No rollback strategy
        # SECURITY ISSUE: No verification of deployment health
    
    # SECURITY ISSUE: No DAST scanning post-deployment
    # SECURITY ISSUE: No compliance validation
