name: Template for unit-test

on:
  # This is a reusable workflow
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        role-session-name: github-oidc
        aws-region: ${{ vars.AWS_REGION }}
    
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name my-cluster --region ${{ vars.AWS_REGION }}
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f infra/deployment.yaml

    # SECURITY ISSUE: No validation of Kubernetes manifests
    # SECURITY ISSUE: No rollback strategy
    # SECURITY ISSUE: No verification of deployment health