name: unit-test

on:
  # This is a reusable workflow
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2

      - name: Build Docker image
        working-directory: ./app
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: github-oidc
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag  ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}