name: unit-test

on:
  # This is a reusable workflow
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: github-oidc
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e #v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
          pip install pytest
    
      - name: Build Docker image
        working-directory: ./app
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag  ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
          docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}