name: unit-test

on:
  # This is a reusable workflow
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2
      
      - name: Set up Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e #v2
        with:
          python-version: '3.9'

      - name: Build Docker image
        working-directory: ./app
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:${{ github.sha }} .